version: "3"
services:
  postgres:
    ports:
      - "5432:5432"
    image: postgres
    volumes:
        - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: "RestaurantDb"
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "Password123"
  keycloak:
    image: jboss/keycloak
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - DB_VENDOR = POSTGRES
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_USER=sa
      - DB_PASSWORD=Password123
      - DB_ADDR=postgres
      - DB_DATABASE=RestaurantDb
      - DB_SCHEMA=public
 
volumes:
  postgres_data:
      driver: local