version: "3"
services:
  sql-db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: restaurant_manager_sql_server
    environment: 
        SA_PASSWORD: "Password123"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Express"
    ports: 
        - "1433:1433"